### ISSUE TITLE
[Feature Request] Progressbar

### ISSUE THREAD

**Issue by Rubylion** [mhoeher/opentodolist#10]
I find a progressbar very useful, as I have a lot of projects, where I work on simultaniously. This gives me a better observation, how things go on. Maybe you want to consider adding it.

**Comment by mhoeher** [comment]
Hi @Rubylion,

thanks for the suggestion. Just to get you right: Do you mean you'd like to have a kind of progress indication for todo lists (either on the library overview page or inside a todo list)? If so, I think it's fine to add this (there's even already an issue for this in the project's issue tracker over on GitLab.com, see https://gitlab.com/rpdev/opentodolist/issues/80).

Otherwise (especially if it helps in the meanwhile): For todos, there is already some kind of progress indicator. If you add tasks inside a todo and start completing them, you get a progress overlay when viewing the todo inside any listing in the app.

**Comment by Rubylion** [comment]
Hi. I meant a manualy adjustable progressbar. just a simple line or rectangle with a button to adjust. It could be adjusted in the task tab, but should show up in the list, too.

**Comment by mhoeher** [comment]
Ah, understood. I will think about how to add it ;-)

**Comment by mhoeher** [comment]
FYI: Here's the tracking issue over at GitLab: https://gitlab.com/rpdev/opentodolist/issues/204

**Comment by Rubylion** [comment]
thanx

**Comment by mhoeher** [comment]
Sorry it took so long, but the latest release (v3.11) allows you to set a progress value on todos manually ;-)
