### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [mhoeher/opentodolist#100]
The scanner at IzzyOnDroid reported:

```
! repo/net.rpdev.opentodolist_9246.apk declares flag(s): usesCleartextTraffic
! repo/net.rpdev.opentodolist_9246.apk declares sensitive permission(s):
  android.permission.READ_EXTERNAL_STORAGE*
```

Could you please clarify

* what cleartext (unencrypted HTTP) connections are needed, where to and what for
* what for the app needs `WRITE_EXTERNAL_STORAGE` (which triggered `READ_EXTERNAL_STORAGE` to be granted implicitly)?

Thanks in advance!

**Comment by mhoeher** [comment]
Moin moin!

Sure :)

Regarding the HTTP connections: OpenTodoList implements sync against various backends, among them WebDAV (and derivatives like NextCloud and ownCloud). Although the app defaults to using HTTPS, the user is allowed to request sync against an HTTP only server - hence the flag.

And regarding the WRITE_EXTERNAL_STORAGE: The app allows to create libraries in arbitrary locations. This also used to work in Android, so you could store a library (which is basically just a folder with a specific file/sub-folder structure) anywhere and use some other app to sync the data. However, I think with recent Android versions, this flag more or less is useless, because file system access is further sandboxed (so I think in theory, the permission could be removed, but then... not sure if users are out there relying on it).

Hope that answers your question!

**Comment by IzzySoft** [comment]
Thanks for your prompt reply! Added them all to the app's "green list" then:

![image](https://github.com/user-attachments/assets/d5a1bb7b-1529-4154-8ac6-e22d5ff2685c)

As for storage: your app requires Android 6+ – so have you considered covering that via SAF (Storage Access Framework)? If it's just a single (or a few) hand-picked location, and needs no extras/specifics like "directly in the SD card root", or image folders (a huge mess with those specifics between Android 5 and 11 with each version handling that differently), it should match the purpose and then would not need the storage permissions. It's basically your sandbox then, restricting the app to exactly the folder(s) picked (well, and sub-directories inside the picked location of course).

**Comment by mhoeher** [comment]
Hey, sorry for the late reply!

Thanks for the heads up. I also assume I could simply drop the flag as with modern, non-rooted versions of Android, apps anyway cannot "leave" their sandbox.

Btw: I cannot  directly use the SAF. The app is built on top of Qt, I use whatever I/O Qt implements to be platform agnostic. Everything else would be too much overhead for me 😉  

Anyway, closing this one. If you have additional questions, please let me know! 😃

**Comment by IzzySoft** [comment]
> Thanks for the heads up. I also assume I could simply drop the flag as with modern, non-rooted versions of Android, apps anyway cannot "leave" their sandbox.

Not sure what you mean there – but you will know what you're doing :wink:

> The app is built on top of Qt, I use whatever I/O Qt implements to be platform agnostic.

Makes sense, thanks!
