### ISSUE TITLE
Feature request - Today view

### ISSUE THREAD

**Issue by TobiasDev** [mhoeher/opentodolist#16]
I added dates to almost all my tasks, but they don't show up in the scheduled list. Is that a bug? Or is it only meant to show tasks planned for later? 

I would love to see a Today and Tomorrow view, either in the scheduled tab, or in it's one. Just so I can easily every morning check what I have to do today. :)

Something else, that would be nice would be to have a sort todo-list after dates. So it sorts them in the order they are planned and keep the ones without date at the bottom.

**Comment by mhoeher** [comment]
What you describe sounds a bit like a bug. :-o

Actually, the schedule view has the sections **Today**, **Later this week**, **Next Week**, **Coming Next** and **Overdue**. Looking at the current implementation, I just realise that I also wanted a **Tomorrow** section (and already considered it a bug that items scheduled for the next day only show up in *Later this week*... so, thanks for the gentle reminder ;-) ).

I just tried to reproduce the behavior, however, when I create a new item here and set the due date to the current date, it is shown in the *Today* section. I bet, this might be due to some stupid time zone calculation. Could you maybe share some more details about your system (especially operating system where this happens and your locale settings)?

Regarding the sort functionality: Yes, I agree, this seems to be a useful addition ;-) I've created [this issue](https://gitlab.com/rpdev/opentodolist/issues/235) in the Gitlab project to track implementation of this feature and assigned it to v3.14 (due end of July).

**Comment by TobiasDev** [comment]
I'm on popOS and in GMT+1, Berlin Germany. (I think it is GMT+1). :D

**Comment by TobiasDev** [comment]
BTW, should I move these things over to Gitlab? If that is your main platform. :) Just missed that, but I can just create issues there, if you rather have them there.

**Comment by mhoeher** [comment]
Thanks, I'll check if I can somehow reproduce on my side. I've created [this issue](https://gitlab.com/rpdev/opentodolist/issues/236) on Gitlab to track this.

For the future: If it's okay for you, you can also directly create issues on Gitlab ;-) That would in fact be a bit easier for me (as the project is developed there and Github is actually just a mirror and used for releases of the app).

**Comment by mhoeher** [comment]
I worked a bit on the app today. It now has a tomorrow section. In addition, I also changed the calculation of the time boundaries a bit, so if you like, you could try out e.g. the [AppImage](https://gitlab.com/rpdev/opentodolist/-/jobs/238338580/artifacts/file/build-ubuntu/OpenTodoList-x86_64.AppImage) from the latest master build and see, if the schedule view now works properly ;-)

In addition, this build also has the background images removed (as discussed in #14) to improve readability.

**Comment by TobiasDev** [comment]
Yup! The issue seems fixed for me! :)
