### ISSUE TITLE
Backup or export

### ISSUE THREAD

**Issue by xausy** [mhoeher/opentodolist#21]
Unfortunately I suffered data loss when synchronizing my entries across several different operating systems. Is it possible to export the entries or create a backup?

**Comment by mhoeher** [comment]
Hi @xausy,

First of all: I am very sorry to hear you lost some data! I hope whatever you lost was not too sensitive/important.

Regarding your request/question: This depends.

OpenTodoList manages your items in what it calls *libraries*. Each library is - kind of - just a simple folder which in turn has some sub-folders and these eventually contain simple `JSON` files. Each item (i.e. each todo list, each todo, each task, each image and each note) is represented as one file in such a library folder.

If you opted to create a library which you sync via the built in mechanisms on e.g. NextCloud or ownCloud, you could even be lucky: Both support (as far as I know) file versioning, so you might even be able to restore some files via their web interface. OpenTodoList by default creates libraries in the top level `OpenTodoList` directory. Each library is stored in a sub-folder which has a randomly generated ID as name.

If you are using other mechanisms to sync (e.g. sync clients of other cloud providers), you can just regularly create snapshots of these library folders.

Of course, the app also could be extended to create backups on its own from time to time. Maybe you could elaborate a bit on your workflow and describe, how you would imagine such a backup to look like? Thanks in advance!

Additionally, I would also be curious about what led to the data lost in the first place? Maybe some simple tweaks in the app could help to prevent such incidents in the future.

**Comment by mhoeher** [comment]
Closing this one for now.

There were several findings in the past that explain data loss due to sync - they have been fixed and the new sync library meanwhile used should anyway be more reliable anyway.

Considering the backup suggestion: When syncing via a web service, the easiest way would be to regularly create a copy of the `OpenTodoList` folder created on the server, as it contains everything essential. For now, I would rather not implement a client side backup.
