### ISSUE TITLE
Smaller views

### ISSUE THREAD

**Issue by huste** [mhoeher/opentodolist#31]
First, I really love this app because it syncs individual items unlike other TODO-List apps. So no more overwriting each others TODO items just because you happen to do it within the sync interval.

In terms of oversight, it would be really nice, if items in the TODO lists took up less vertical space. More compact views would help a great deal.

**Comment by huste** [comment]
Sorry, I just saw, that there's a gitlab project as well. Shall I move all the suggestions there?

**Comment by mhoeher** [comment]
Hi @huste,

thanks a lot for your feedback! Regarding your request: I am using the standard layout provided by the underlying Qt library for the lists - I think they are using the suggested spacing for list items from the Material theme.

That said, I can still think of the following:

- The Material style can be configured to be *dense*. My understanding is, that this will generally reduce some spacing. I could add an option to the app to enable this.
- I could also try to add a dedicated option to have less vertical space only in todo/task lists (could require some more work, but should definitely be doable). However, here I need to be careful, because Qt (and the general Material style) picked the spacing for a reason (so it is touch friendly). However, especially on a desktop system, a reduced space definitely makes sense.

What do you think?

Regarding Gitlab: Don't worry. I'll create a follow up issue (and link it here, for others who might stumble across this issue here).

**Comment by huste** [comment]
While I can understand the approach that Qt does all the work, it's still a real waste of space. So enabling the dense mode would be worth a try. I am on Android BTW, and here's where I believe it to be hard to balance the available space with the possibility to hit the desired entries with the finger. I'll add screenshots to #33

**Comment by mhoeher** [comment]
No problem, and yes, due to different device resolutions and pixel densities, rendering might vary. I added an issue over at Gitlab to allow switching to the dense variant of the Material theme: https://gitlab.com/rpdev/opentodolist/-/issues/396

Feel free to subscribe to it. I'll also update this issue here once something is available for testing.

If the dense variant alone is not sufficient, I think we can still check if we can change the rendering of list items to make them even more compact afterwards.

**Comment by huste** [comment]
I'll just close this one here, no need to have a duplicate here at github.
