### ISSUE TITLE
Feature request: Hide completed subtasks

### ISSUE THREAD

**Issue by huste** [mhoeher/opentodolist#34]
In main tasks, you can choose to hide completed items, in subtasks, you can't. In combination with #31 this would not be so much of a problem, but when you have 20 items to buy it's easy to lose track.
Maybe a different display of completed tasks (coloured check circle? shaded background?) would help, too.

**Comment by mhoeher** [comment]
Technically, both suggestions would not be a problem. Handling of tasks is internally very similar to that of todos, so having an option to hide checked tasks is doable in no time :wink: 

The same applies for a changes visual representation of completed tasks. However, I would then try to keep both todo and task listings in a similar way (i.e. also render completed todos in the same way).

What of the would you prefer?

**Comment by huste** [comment]
Thanks for the reply. From my experience with OpenTasks which I removed because of the sync interval and constantly overwriting each others changes, I can say that their approach of showing the check mark in colour and the text in strike through is a very good visual indication of a completed TODO-list item. So I'd rather vote for strike throuh in combination with a coloured check mark (maybe just choose a darker shade of the item colour itself)

**Comment by mhoeher** [comment]
I shortly used OpenTasks in the past, however, that's a long time ago. But I'll check out how they are doing it.

For now, I simply created two issues over at GitLab:

- Via https://gitlab.com/rpdev/opentodolist/-/issues/393, I'll implement hiding of completed tasks.
- And via https://gitlab.com/rpdev/opentodolist/-/issues/394, I'll look into rendering completed todos and tasks differently.

Feel free to subscribe to these to get updates - otherwise I'll update this issue here once something is available for testing :wink:

**Comment by huste** [comment]
As with the ohters, closing here, they have a better life over at gitlab :)
