### ISSUE TITLE
The fonts look weird on Android

### ISSUE THREAD

**Issue by gerroon** [mhoeher/opentodolist#37]
Hi

I just installed this (3.31.1) on Android 9, (using an OS based on LineageOS) and the fonts look really weird. Is there a way to change to some another font? Please see the inconsistencies between spacing and the capital letters.

![Screenshot_20210208-191835](https://user-images.githubusercontent.com/8519469/107302469-0ee25880-6a43-11eb-8133-af9d607e88ec.jpg)

**Comment by mhoeher** [comment]
The app is using the Material theme (as implemented by the underlying Qt library). That theme uses the Google Noto fonts. Can you check, if the font is available on your system? If not, it will probably pick the default Sans-Serif font that is otherwise available.

I unfortunately don't own a Lineage based device (nor do I have a suitable spare one where I could install it) so I cannot test this easily on my side, sorry. But I think I saw that effect in the past on other devices, too.

An alternative might be to include a copy of that font in the APK, but this would increase the download size for everyone, so if this can be solved otherwise, this would probably be the preferred solution :wink:

**Comment by gerroon** [comment]
As far as I can tell my phone is using Google Sans and I did not see the Noto one in the list.

**Comment by mhoeher** [comment]
Yeah, that might explain it. I had a short look into the sources of the Qt Material theme. What they seem to do is request the Roboto font and - if this is not present - Noto, afterwards falling back to whatever the system deems related to these.

Probably Roboto isn't installed, too, right?

I just checked and it seems the Roboto font is not that large, so packaging it with the app should be fine. I'll try to look into this and build a test APK later that week.

**Comment by gerroon** [comment]
Hey thanks for looking into it. I guess distributing it with a suitable font sounds like the way to go. I am persoanlly fine with increased size in the apk, but that is my personal take.

**Comment by mhoeher** [comment]
I created an MR over at GitLab to embed the Roboto font into the app: https://gitlab.com/rpdev/opentodolist/-/merge_requests/247

Could you do me a favor and test the APK (you can download it from the `sign_apks` job in [this pipeline](https://gitlab.com/rpdev/opentodolist/-/pipelines/255085858) one finished)? If the app looks better, I would go ahead and merge the change, so it will be included in the next release :wink:

**Comment by gerroon** [comment]
Hi

I will be happy to test it, but I got in a link maze with that link. I can download and test it if you just give me the direct url to the apk.

**Comment by mhoeher** [comment]
Here you go: https://gitlab.com/rpdev/opentodolist/-/jobs/1024939592/artifacts/browse/build-android/

Just make sure you pick the correct version depending on your phone (nowadays most smartphones run 64bit ARM, so this should be the apk of choice for you: https://gitlab.com/rpdev/opentodolist/-/jobs/1024939592/artifacts/file/build-android/OpenTodoList-Android-arm64-v8a-aligned.apk).

**Comment by gerroon** [comment]
Hi

This looks much better, thanks for the fix.

**Comment by mhoeher** [comment]
Thanks for testing! Just merged the change, so it'll make it into the next release.
