### ISSUE TITLE
Sync problem to WebDAV on Windows Server

### ISSUE THREAD

**Issue by ProNoiser** [mhoeher/opentodolist#62]
Hi, Martin!
Please tell me why OpenToDoList doesn't want to synchronize via WebDAV protocol.
I have a VPS based on Windows Server 2012 on which a WebDAV server is deployed. I tried deploying it inside IIS, tried deploying it on nginx. And in no case does synchronization work, and when you try to establish a connection from other applications and from the file system, everything goes without problems.
Why can't I configure WebDAV to interact with OpenToDoList.
Maybe there is some manual or tricks and subtleties of the WebDAV server settings for working with OpenToDoList?
Deploying NextCloud on Windows Server is impossible in principle, because there is simply no server part of NextCloud for Windows. Only the client. Somehow it's very sad...
Can you help in any way?

Sincerely.
@ProNoiser

**Comment by mhoeher** [comment]
OpenTodoList (or better: The SynqClient library, which implements the WebDAV sync) has some requirements towards the WebDAV servers. In particular, it relies on proper "etags" being generated and used by the server. However, there are a lot of servers which don't - these servers are typically not suitable for a sync.

So why do other apps work: Because not all of them do a real sync but rather fetch the data and push it back once the user is done. However, this is not how OpenTodoList can work - the app is explicitly designed to have a reliable and quick sync, which is impossible to implement without etags.

You can try to run the app from the terminal (start it with `--enable-console` on Windows, otherwise the app "forks" and you won't get any output on the console) to get a bit more insight into what exactly fails.

I know this sucks, however, there is little the  app can do - in this case, it is the server which is to blame.

So how to continue?

- Have you considered using Docker or WSL to run a NextCloud server in a container? This would allow you to run even a complex LAMP stack on a Windows server.
- There might be chances to get the type of server compatible by implementing workarounds in the app. If you'd like to explore this path, I would need a test account so I can first run the unit tests against the server and try to find out what exactly is the issue and maybe find a proper way to make the sync work. However, as a disclaimer, please note that there is not guarantee that this might lead to a solution. Some servers are simply "too broken" to safely use them as a sync backend.
