### ISSUE TITLE
Use Open ToDo List in Workgroup

### ISSUE THREAD

**Issue by ProNoiser** [mhoeher/opentodolist#63]
Hi, Martin!
There are several people who are united by working on their project.
There is a project curator who should see all the tasks distributed to the project participants.
But project participants should not see the tasks of other participants.
Those the idea is that the boss sees everyone, and the employees only themselves.
Is it possible to implement such a scheme in Open ToDo List?

**Comment by mhoeher** [comment]
I guess it should be possible to get to something like that, although I don't know if this completely covers what you had in mind. Let me explain a bit:

OpenTodoList organises items in "libraries". Each library is basically a folder which is stored on disk and which can be synced (e.g. via WebDAV and hence NextCloud or ownCloud or - in a hopefully near future release - via Dropbox) across several devices.

In fact, when synchronising a library, it can also be shared with other people. I do this (we have e.g. at home a shared library where we maintain among others our grocery lists). Currently, OpenTodoList has no built-in GUI for sharing a library, but it is perfectly possible to share the library manually with other users via the server. On the WebDAV server, OpenTodoList creates a folder called `OpenTodoList` in which it stores each library (the folder name is a random UUID, so you'll certainly agree that eventually we need a nice GUI in OpenTodoList to do the sharing).

In case of using NextCloud or ownCloud, when you share a single library folder with someone else, it will show up in their top level folder (e.g. while you see it as `/OpenTodoList/{XXXXX}`, someone you share with sees it just as `/{XXXXX}`). However, OpenTodoList will check both locations for libraries when you try to add them to a device, so this is nothing to worry about.

Anyway, that said, what you could do to implement a scenario as you described is the following:

- The "boss" could create one library per worker and sync it via a server.
- Then, he would share the library folder (and only that) with the worker it is intended for.
- The workers would connect to the WebDAV server and when trying to add the existing library, should see the one created for them.

For the "worker" side, this should probably be okay. I guess, for the "boss" side some extensions in OpenTodoList would be nice as well. For example, there currently is no way to see items from all libraries one has at the same time (and hence, search/filter/...).

Also note that with this approach, it is not possible to create e.g. a "shared" todo list, where only the boss sees all todos and then he assigns single items to dedicated workers. This is because a "complex" item (such as a todo list) cannot span multiple libraries. This is by design and also won't change - so if this is what you had in mind, then unfortunately the answer is "no".
