### ISSUE TITLE
Create a portable Windows version

### ISSUE THREAD

**Issue by hynow** [mhoeher/opentodolist#67]
The cross-platform nature and full control over storing and syncing the data is amazing.  Thank you for that.  It is very rare.  Being able to run it on Windows without administrator privileges would be extremely helpful.  This way, it would always be accessible, such as at work, a library, or borrowed computer.

**Comment by mhoeher** [comment]
Hi @hynow,

first of all thank you for raising this and the other requests - any kind of feedback is highly welcome 😉 

Before I start going into the details of this and the other issues, one thing: OpenTodoList is developed over at [GitLab](https://gitlab.com/rpdev/opentodolist) - all development takes place there and also issues (which I use for managing the work on the app) are created there. The project here on GitHub is merely a mirror and used to deploy the release binaries.

If you plan to provide further suggestions or feedback, it would be really helpful if you could do so directly on GitLab - simply because it rids me of some extra work I have to do otherwise. Thanks for considering!

Now, coming to your actual input:

If I get you right, you would like to be able to create an installation of the app on e.g. a USB thumb drive, run it from there and also save any created libraries and configurations "next to" the app, so when you plug the same stick into another computer, you could start the app from there and have everything immediately available, is this correct?

There is actually already a similar feature request on GitLab for this: https://gitlab.com/rpdev/opentodolist/-/issues/464 

I guess this goes into the same direction, right?

**Comment by mhoeher** [comment]
There meanwhile is a portable version of the app which allows simple download as zip. Hence, closing for now.
