### ISSUE TITLE
Location of app files, notes, etc on Linux

### ISSUE THREAD

**Issue by sid-the-sloth** [mhoeher/opentodolist#74]
Sorry, can't figure where the app stores the project files (notes, etc.) on Linux operating systems.

**Comment by mhoeher** [comment]
The concrete place varies, depending on th way how you installed the app (AppImage vs Flatpak vs Snap).

Internally, OpenTodoList uses a system specific location to store "application local data" (look for `AppLocalDataLocation` in the documentation of [QStandardPaths](https://doc.qt.io/qt-6/qstandardpaths.html) to learn more). That means, for Linux, we typically use `$HOME/.local/share/OpenTodoList`. However, when running the app using e.g. Flatpak, the location is different (this is due to how Flatpak works and abstracts the app storage and config locations). In the Flatpak case, all the data is stored in `$HOME/.var/app/net.rpdev.OpenTodoList`.

In addition, these locations can be tweaked by setting some environment variables (e.g. `XDG_DATA_DIRS`), so it might be worth checking if your distribution sets them to something else.

Hope that helps!

**Comment by sid-the-sloth** [comment]
Thank you, I am using the appimage, did save a new file in OpenTodoList, but I don't see anything under `$HOME/.local/share/`, the `OpenTodoList` folder is not created, yet I don't know where it's saving...

EDIT: your app is saving under: `$HOME/.local/share/RPdev/OpenTodoList/` :exclamation:

**Comment by mhoeher** [comment]
Yes, could be. As mentioned, the app is using some APIs provided by the underlying Qt framework to pick a suitable path - as an "organisation" name is present in the app (this is "RPdev"), this one as well is taken into the path.

Anyway: Does this "solve" your problem? Any additional help/information required or can I go ahead and close this issue? 😉 

PS: You can also start the app on the command line. This should reveal some debug information - including where libraries and other stuff is loaded from.

**Comment by sid-the-sloth** [comment]
Yes, thanks, you can close the issue.
